# Generated by Django 4.1.4 on 2022-12-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_name", models.CharField(max_length=200)),
                ("audio_file", models.FileField(upload_to="audio/")),
                ("tag", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Audio_table",
            },
        ),
        migrations.CreateModel(
            name="Transcribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("data", models.CharField(max_length=100000)),
                ("data2", models.CharField(max_length=100000)),
                ("created_at", models.DateField()),
                (
                    "audio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workers.audios"
                    ),
                ),
            ],
        ),
    ]
